name: semgrepper
description: Run Semgrep and output results in GitHub Annotations format.
inputs:
  config:
    description: --config option value for semgrep ci.
    required: false
    default: ".semgrep"
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.config }}
branding:
  color: green
  icon: eye
